"""initial schema

Revision ID: c8e178707e87
Revises: 
Create Date: 2026-03-02 22:30:28.640872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e178707e87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advertiser_id', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('target_product', sa.String(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('max_cpc', sa.Float(), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bids_advertiser_id', 'bids', ['advertiser_id'], unique=False)
    op.create_index('ix_bids_is_active', 'bids', ['is_active'], unique=False)
    op.create_index('ix_bids_product_category', 'bids', ['product_category'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('wallet_type', sa.String(), nullable=False),
    sa.Column('ydm_balance', sa.Float(), nullable=False),
    sa.Column('eth_balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('agents', 'performance_score',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('agents', 'trust_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agents', 'commission_earned_total',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('agents', 'daily_budget',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('agents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('ix_agents_created_at', 'agents', ['created_at'], unique=False)
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_index('ix_agents_type', 'agents', ['type'], unique=False)
    op.alter_column('deals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('deals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('deals', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.alter_column('iot_devices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('iot_devices', 'last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('iot_devices', 'auto_order_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('iot_devices', 'budget_limit',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('iot_devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('iot_devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('ix_iot_devices_status', 'iot_devices', ['status'], unique=False)
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_shop_id', 'products', ['shop_id'], unique=False)
    op.alter_column('shops', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('shops', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('shops', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.alter_column('smart_contracts', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('smart_contracts', 'execution_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('smart_contracts', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('smart_contracts', 'monthly_budget',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('smart_contracts', 'spent_this_month',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('smart_contracts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('smart_contracts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('ix_smart_contracts_agent_id', 'smart_contracts', ['agent_id'], unique=False)
    op.create_index('ix_smart_contracts_is_active', 'smart_contracts', ['is_active'], unique=False)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index('ix_transactions_advertiser_id', 'transactions', ['advertiser_id'], unique=False)
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_publisher_id', 'transactions', ['publisher_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_publisher_id', table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_index('ix_transactions_advertiser_id', table_name='transactions')
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_index('ix_smart_contracts_is_active', table_name='smart_contracts')
    op.drop_index('ix_smart_contracts_agent_id', table_name='smart_contracts')
    op.alter_column('smart_contracts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('smart_contracts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('smart_contracts', 'spent_this_month',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('smart_contracts', 'monthly_budget',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('smart_contracts', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('smart_contracts', 'execution_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('smart_contracts', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.alter_column('shops', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('shops', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('shops', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_products_shop_id', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_index('ix_iot_devices_status', table_name='iot_devices')
    op.alter_column('iot_devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('iot_devices', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('iot_devices', 'budget_limit',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('iot_devices', 'auto_order_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('iot_devices', 'last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('iot_devices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.alter_column('deals', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('deals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('deals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_agents_type', table_name='agents')
    op.drop_index('ix_agents_status', table_name='agents')
    op.drop_index('ix_agents_created_at', table_name='agents')
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('agents', 'daily_budget',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('agents', 'commission_earned_total',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('agents', 'trust_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agents', 'performance_score',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.drop_table('wallets')
    op.drop_index('ix_bids_product_category', table_name='bids')
    op.drop_index('ix_bids_is_active', table_name='bids')
    op.drop_index('ix_bids_advertiser_id', table_name='bids')
    op.drop_table('bids')
    # ### end Alembic commands ###
