"""add affiliate_offers table

Revision ID: fe0e8e87a9d0
Revises: e7d13100d7f1
Create Date: 2026-03-03 03:32:01.447496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0e8e87a9d0'
down_revision: Union[str, Sequence[str], None] = 'e7d13100d7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('advertiser_name', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_offers_commission', 'affiliate_offers', ['commission_rate'], unique=False)
    op.create_index('ix_affiliate_offers_last_updated', 'affiliate_offers', ['last_updated'], unique=False)
    op.create_index('ix_affiliate_offers_network', 'affiliate_offers', ['network'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_affiliate_offers_network', table_name='affiliate_offers')
    op.drop_index('ix_affiliate_offers_last_updated', table_name='affiliate_offers')
    op.drop_index('ix_affiliate_offers_commission', table_name='affiliate_offers')
    op.drop_table('affiliate_offers')
    # ### end Alembic commands ###
